export const STOPWORDS = new Set([
  "a", "about", "after", "again", "against", "all", "also", "am", "an", "and",
  "any", "are", "as", "at", "be", "because", "been", "before", "being", "between",
  "both", "but", "by", "can", "could", "did", "do", "does", "doing", "down",
  "during", "each", "few", "for", "from", "further", "had", "has", "have",
  "having", "he", "her", "here", "hers", "him", "his", "how", "i", "if", "in",
  "into", "is", "it", "its", "itself", "just", "may", "me", "might", "more",
  "most", "my", "no", "nor", "not", "now", "of", "off", "on", "once", "one",
  "only", "or", "other", "our", "out", "over", "own", "same", "say", "says",
  "said", "she", "should", "so", "some", "such", "than", "that", "the", "their",
  "them", "then", "there", "these", "they", "this", "those", "through", "to",
  "too", "under", "until", "up", "very", "was", "we", "were", "what", "when",
  "where", "which", "while", "who", "whom", "why", "will", "with", "would",
  "you", "your", "new", "news", "latest", "update", "live", "video", "watch",
  "opinion", "analysis", "breaking", "report", "reports", "reported", "according",
  "people", "year", "years", "day", "days", "week", "today", "yesterday",
  "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
  "told", "including", "since", "still", "even", "back", "around", "many",
  "much", "well", "way", "get", "got", "make", "made", "take", "taken", "see",
  "seen", "know", "going", "want", "use", "used", "using", "world", "country",
  "government", "official", "officials", "state", "states", "first", "last",
  "time", "times", "two", "three", "four", "five", "percent", "per", "via",
  "amid", "near", "across", "into", "onto", "upon", "within", "without", "among",
  "several", "another", "every", "something", "someone", "home", "show", "shows",
  "call", "called", "calls", "come", "comes", "came", "look", "looks", "like",
  "please", "read", "full", "story", "stories", "meeting", "meetings", "talks",
  "visit", "visits", "demand", "demands", "expect", "expects", "challenge",
  "challenges", "general", "assembly",
]);
