/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as HealthRouteImport } from './routes/health'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ApiClustersRouteImport } from './routes/api/clusters'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTimelineRouteImport } from './routes/api/timeline'
import { Route as ClustersIdRouteImport } from './routes/clusters.$id'
import { Route as IngestTriggerRouteImport } from './routes/ingest.trigger'
import { Route as ApiClustersIdRouteImport } from './routes/api/clusters.$id'
import { Route as ApiIngestTriggerRouteImport } from './routes/api/ingest.trigger'
import { Route as IngestStatusJobIdRouteImport } from './routes/ingest.status.$jobId'
import { Route as ApiIngestStatusJobIdRouteImport } from './routes/api/ingest.status.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClustersRoute = ApiClustersRouteImport.update({
  id: '/api/clusters',
  path: '/api/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimelineRoute = ApiTimelineRouteImport.update({
  id: '/api/timeline',
  path: '/api/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersIdRoute = ClustersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClustersRoute,
} as any)
const IngestTriggerRoute = IngestTriggerRouteImport.update({
  id: '/ingest/trigger',
  path: '/ingest/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClustersIdRoute = ApiClustersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClustersRoute,
} as any)
const ApiIngestTriggerRoute = ApiIngestTriggerRouteImport.update({
  id: '/api/ingest/trigger',
  path: '/api/ingest/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestStatusJobIdRoute = IngestStatusJobIdRouteImport.update({
  id: '/ingest/status/$jobId',
  path: '/ingest/status/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestStatusJobIdRoute = ApiIngestStatusJobIdRouteImport.update({
  id: '/api/ingest/status/$jobId',
  path: '/api/ingest/status/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/clusters': typeof ClustersRouteWithChildren
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/api/clusters': typeof ApiClustersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/timeline': typeof ApiTimelineRoute
  '/clusters/$id': typeof ClustersIdRoute
  '/ingest/trigger': typeof IngestTriggerRoute
  '/api/clusters/$id': typeof ApiClustersIdRoute
  '/api/ingest/trigger': typeof ApiIngestTriggerRoute
  '/ingest/status/$jobId': typeof IngestStatusJobIdRoute
  '/api/ingest/status/$jobId': typeof ApiIngestStatusJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/clusters': typeof ClustersRouteWithChildren
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/api/clusters': typeof ApiClustersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/timeline': typeof ApiTimelineRoute
  '/clusters/$id': typeof ClustersIdRoute
  '/ingest/trigger': typeof IngestTriggerRoute
  '/api/clusters/$id': typeof ApiClustersIdRoute
  '/api/ingest/trigger': typeof ApiIngestTriggerRoute
  '/ingest/status/$jobId': typeof IngestStatusJobIdRoute
  '/api/ingest/status/$jobId': typeof ApiIngestStatusJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/clusters': typeof ClustersRouteWithChildren
  '/health': typeof HealthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/api/clusters': typeof ApiClustersRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/timeline': typeof ApiTimelineRoute
  '/clusters/$id': typeof ClustersIdRoute
  '/ingest/trigger': typeof IngestTriggerRoute
  '/api/clusters/$id': typeof ApiClustersIdRoute
  '/api/ingest/trigger': typeof ApiIngestTriggerRoute
  '/ingest/status/$jobId': typeof IngestStatusJobIdRoute
  '/api/ingest/status/$jobId': typeof ApiIngestStatusJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/clusters'
    | '/health'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/timeline'
    | '/api/clusters'
    | '/api/health'
    | '/api/timeline'
    | '/clusters/$id'
    | '/ingest/trigger'
    | '/api/clusters/$id'
    | '/api/ingest/trigger'
    | '/ingest/status/$jobId'
    | '/api/ingest/status/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/clusters'
    | '/health'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/timeline'
    | '/api/clusters'
    | '/api/health'
    | '/api/timeline'
    | '/clusters/$id'
    | '/ingest/trigger'
    | '/api/clusters/$id'
    | '/api/ingest/trigger'
    | '/ingest/status/$jobId'
    | '/api/ingest/status/$jobId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/clusters'
    | '/health'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/timeline'
    | '/api/clusters'
    | '/api/health'
    | '/api/timeline'
    | '/clusters/$id'
    | '/ingest/trigger'
    | '/api/clusters/$id'
    | '/api/ingest/trigger'
    | '/ingest/status/$jobId'
    | '/api/ingest/status/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ClustersRoute: typeof ClustersRouteWithChildren
  HealthRoute: typeof HealthRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  ApiClustersRoute: typeof ApiClustersRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTimelineRoute: typeof ApiTimelineRoute
  IngestTriggerRoute: typeof IngestTriggerRoute
  ApiIngestTriggerRoute: typeof ApiIngestTriggerRoute
  IngestStatusJobIdRoute: typeof IngestStatusJobIdRoute
  ApiIngestStatusJobIdRoute: typeof ApiIngestStatusJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clusters': {
      id: '/api/clusters'
      path: '/api/clusters'
      fullPath: '/api/clusters'
      preLoaderRoute: typeof ApiClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/timeline': {
      id: '/api/timeline'
      path: '/api/timeline'
      fullPath: '/api/timeline'
      preLoaderRoute: typeof ApiTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/$id': {
      id: '/clusters/$id'
      path: '/$id'
      fullPath: '/clusters/$id'
      preLoaderRoute: typeof ClustersIdRouteImport
      parentRoute: typeof ClustersRoute
    }
    '/ingest/trigger': {
      id: '/ingest/trigger'
      path: '/ingest/trigger'
      fullPath: '/ingest/trigger'
      preLoaderRoute: typeof IngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clusters/$id': {
      id: '/api/clusters/$id'
      path: '/$id'
      fullPath: '/api/clusters/$id'
      preLoaderRoute: typeof ApiClustersIdRouteImport
      parentRoute: typeof ApiClustersRoute
    }
    '/api/ingest/trigger': {
      id: '/api/ingest/trigger'
      path: '/api/ingest/trigger'
      fullPath: '/api/ingest/trigger'
      preLoaderRoute: typeof ApiIngestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest/status/$jobId': {
      id: '/ingest/status/$jobId'
      path: '/ingest/status/$jobId'
      fullPath: '/ingest/status/$jobId'
      preLoaderRoute: typeof IngestStatusJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/status/$jobId': {
      id: '/api/ingest/status/$jobId'
      path: '/api/ingest/status/$jobId'
      fullPath: '/api/ingest/status/$jobId'
      preLoaderRoute: typeof ApiIngestStatusJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClustersRouteChildren {
  ClustersIdRoute: typeof ClustersIdRoute
}

const ClustersRouteChildren: ClustersRouteChildren = {
  ClustersIdRoute: ClustersIdRoute,
}

const ClustersRouteWithChildren = ClustersRoute._addFileChildren(
  ClustersRouteChildren,
)

interface ApiClustersRouteChildren {
  ApiClustersIdRoute: typeof ApiClustersIdRoute
}

const ApiClustersRouteChildren: ApiClustersRouteChildren = {
  ApiClustersIdRoute: ApiClustersIdRoute,
}

const ApiClustersRouteWithChildren = ApiClustersRoute._addFileChildren(
  ApiClustersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ClustersRoute: ClustersRouteWithChildren,
  HealthRoute: HealthRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  ApiClustersRoute: ApiClustersRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiTimelineRoute: ApiTimelineRoute,
  IngestTriggerRoute: IngestTriggerRoute,
  ApiIngestTriggerRoute: ApiIngestTriggerRoute,
  IngestStatusJobIdRoute: IngestStatusJobIdRoute,
  ApiIngestStatusJobIdRoute: ApiIngestStatusJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
